### ISSUE TITLE
Réponse - POST

### ISSUE THREAD

**Issue by cmariot** [cmariot/webserv#6]
Ajoutez ce qu'il y a à faire ou vérifier ici.

- [x] Merge de la branche d'Abensett
- [x] Selection du bloc location correspondant à la requête (déjà fait dans GET, à mutualiser si pas déjà fait)
- [x] Vérifier que post est autorisé
- [x] Vérifier que l'upload est autorisé
- [x] Construire l'upload_path
- [x] Upload de fichiers / formulaires
- [x] CGI
- [x] max body size prise en compte
- [x] Pages d'erreurs à prendre en compte
- [x] Fichier déjà existant, permissions ...

**Comment by Abensett** [comment]
* [x] add different status code
* [x] add same things but with delete
* [x] check leaks
